image: debian

stages:
  - generate
  - build

# install libraries
before_script:
  - apt-get update
  - apt-get install clang cmake
  - apt-get install python3 python3-pip python3-virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python3 -V
  - pip3 install libyang
  - pip3 install Jinja2
  # TODO: get sysrepo and libyang and build them

generate:
  stage: generate

  script:
    - mkdir generated
    - mkdir generated/ietf-system generated/ietf-interfaces
    - python3 src/sysrepo-plugin-generator.py -d yang -m ietf-system -o gen/ietf-system -M ietf-system
    - python3 src/sysrepo-plugin-generator.py -d yang -m ietf-interfaces -o gen/ietf-interfaces -M ietf-interfaces
  
  artifacts:
    paths:
      - generated/

build:
  stage: build

  script:
    - mkdir generated/ietf-system/build
    - mkdir generated/ietf-interfaces/build
  
  artifacts:
    paths:
      - generated/ietf-system/build
      - generated/ietf-interfaces/build
