image: debian

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - generate
  - build

# install libraries
before_script:
  - apt-get update
  - apt-get -y install clang cmake git libpcre2-dev libsystemd-dev
  - apt-get -y install python3 python3-pip
  - git clone https://github.com/CESNET/libyang.git
  - git clone https://github.com/sysrepo/sysrepo.git
  - cd libyang; git checkout devel; mkdir build; cd build; cmake .. -DCMAKE_C_COMPILER=clang; make -j install; cd ../../
  - cd sysrepo; git checkout devel; mkdir build; cd build; cmake .. -DCMAKE_C_COMPILER=clang; make -j install; cd ../../
  - pip3 install libyang
  - pip3 install Jinja2

generate:
  stage: generate

  script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - mkdir generated
    - mkdir generated/ietf-system
    - echo $LD_LIBRARY_PATH
    - python3 src/sysrepo-plugin-generator.py -d yang -m ietf-system -o generated/ietf-system -M ietf-system
  
  artifacts:
    paths:
      - generated/

build:
  stage: build

  script:
    - mkdir generated/ietf-system/build
    - cmake -S generated/ietf-system -B generated/ietf-system/build -DSYSTEMD_IFINDEX=1 -DCMAKE_C_COMPILER=clang
  
  artifacts:
    paths:
      - generated/ietf-system/build
