image: debian

stages:
  - generate
  - build

# install libraries
before_script:
  - apt-get update
  - apt-get -y install clang cmake git libpcre2-dev
  - apt-get -y install python3 python3-pip
  - git clone https://github.com/CESNET/libyang.git
  - git clone https://github.com/sysrepo/sysrepo.git
  - cd libyang; git checkout devel; mkdir build; cd build; cmake .. -DCMAKE_C_COMPILER=clang; make -j install; cd ../../
  - cd sysrepo; git checkout devel; mkdir build; cd build; cmake .. -DCMAKE_C_COMPILER=clang; make -j install; cd ../../
  - pip3 install libyang
  - pip3 install Jinja2
  # TODO: get sysrepo and libyang and build them

generate:
  stage: generate

  script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - mkdir generated
    - mkdir generated/ietf-system generated/ietf-interfaces
    - echo $LD_LIBRARY_PATH
    - python3 src/sysrepo-plugin-generator.py -d yang -m ietf-system -o gen/ietf-system -M ietf-system
    - python3 src/sysrepo-plugin-generator.py -d yang -m ietf-interfaces -o gen/ietf-interfaces -M ietf-interfaces
  
  artifacts:
    paths:
      - generated/

build:
  stage: build

  script:
    - mkdir generated/ietf-system/build
    - mkdir generated/ietf-interfaces/build
  
  artifacts:
    paths:
      - generated/ietf-system/build
      - generated/ietf-interfaces/build
